### ISSUE TITLE
website offline

### ISSUE THREAD

**Issue by Alnoa** [jonblack/arduino-menusystem#10]
link broken >> http://jonblack.org/2012/05/14/arduino-library-for-creating-a-menu-system/
thanks for looking it

**Comment by jonblack** [comment]
The website is down and out for the foreseeable future. I've been meaning to make a github io project page but haven't found the time. In the meantime, the website blog posts are all available in markdown format at https://github.com/jonblack/jonblack.org/tree/master/blog/content/posts. It's not ideal, but is better than nothing I guess.
