### ISSUE TITLE
Menu select() callback missing

### ISSUE THREAD

**Issue by gzabusek** [jonblack/arduino-menusystem#31]
Hello there,

in my case it would be useful to provide also a callback method for when a sub-Menu is selected. It would allow for clean code. Right now we have to check this manually whether a specific menu was selected. Can you please let me know if I just missed something? If not I can start working on the implementation of this today. Let me know if you would like that. Thanks for great lib!

**Comment by jonblack** [comment]
A `Menu` is considered a container for `MenuComponent`'s. Any actions associated with your menu are assumed to be associated with a `MenuItem`. When you `select` a `Menu`, the only expected result is to show what's in that menu.

I'm interested to know why you need to know if a `Menu` has been selected?

**Comment by gzabusek** [comment]
Hello there, its been a while :) But the reason was (i hope i remember precisely) that if one is using dynamic menus like in my case (ie - the submenu is only generated after the parent menu is selected - for instance when the menu is fetched from the network etc). For these reason (allocating / deallocating dynamic menus) it would be useful to have this.

**Comment by jonblack** [comment]
That's a pretty good reasonable use case. I'll keep this open and take a look at it with #20.

**Comment by jonblack** [comment]
I'm gonna close this and resolve it in issue #20. That may not be for the next release.
