### ISSUE TITLE
Add makefiles for examples

### ISSUE THREAD

**Issue by jonblack** [jonblack/arduino-menusystem#33]
Add arduino-mk makefiles for each example.

- [x] current_item
- [x] current_menu
- [x] lcd_nav
- [x] led_matrix
- [x] led_matrix_animated
- [x] pcd8544_nav
- [x] serial_nav

**Comment by eadf** [comment]
Just a suggestion: use` ~/`instead of`/home/jon/`in the makefiles.

**Comment by jonblack** [comment]
:dizzy_face: well spotted!

**Comment by jonblack** [comment]
Turns out Makefiles don't expand `~`. Using `$(HOME)` did the trick.
