### ISSUE TITLE
 void select(boolean reset=false);

### ISSUE THREAD

**Issue by AlexFundorin** [jonblack/arduino-menusystem#45]
Each provided example (version 2.1.1) returns the following error when compiled:

In file included from C:\Users\username\Documents\Arduino\libraries\arduino-menusystem\MenuSystem.cpp:6:0:

C:\Users\username\Documents\Arduino\libraries\arduino-menusystem\MenuSystem.h:86:10: error: candidate is: void MenuSystem::select(boolean)

     void select(boolean reset=false);

          ^

**Comment by jonblack** [comment]
I checked out the `v.2.1.1` tag and added a Makefile for the `serial_nav` and `current_item` examples and both compiled (`serial_nav` required some changes, but not what you mentioned).

In any case, they certainly work in the master branch so a new release will fix this.
