### ISSUE TITLE
Circle menu

### ISSUE THREAD

**Issue by scls19fr** [jonblack/arduino-menusystem#68]
Hello,

in this example pressing `next` display

- Level 1 - Item 1 (Item)

- Level 1 - Item 2 (Item)

- Level 1 - Item 3 (Menu)

pressing again `next` again doesn't change position in menu.

Circle menu ie going (back) to Level 1 - Item 1 (Item) could be a nice experience for users.

Kind regards

**Comment by jonblack** [comment]
`MenuSystem::next` already supports this. Just pass `true` as its argument: `ms.next(true)`.

**Comment by scls19fr** [comment]
Thanks @jonblack I should had a look more deeply in your code
