### ISSUE TITLE
Conflict with Arduino Button Library

### ISSUE THREAD

**Issue by jctsai130** [jonblack/arduino-menusystem#9]
Arduino menusystem is conflict with Arduino Button library

http://playground.arduino.cc/Code/Button

when I instantiate 2 button objects......the menu items will disappear 

Button fireButton = Button(3,BUTTON_PULLUP_INTERNAL);
Button upButton = Button(4,BUTTON_PULLUP_INTERNAL);   // choose the input pin (for a pushbutton)

Let me know if  you can fix it...

Thanks!

**Comment by jonblack** [comment]
No response so closing.
